# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $project = "$(build.sourcesDirectory)\Database"
      $validateProject = $project | invoke-DatabaseBuild
      $buildArtifact = $validatedProject | New-DatabaseBuildArtifact -PackageId Mydatabase -PackageVersion 1.0.$env:Build_BuildID
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

